S3_CONFIG = YAML.load_file("#{Rails.root}/config/s3_config.yml")[Rails.env]
S3_BUCKET_NAME = S3_CONFIG['S3_BUCKET_NAME']
AWS_ACCESS_KEY_ID = S3_CONFIG['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = S3_CONFIG['AWS_SECRET_ACCESS_KEY']