
development:
  adapter: postgresql
  encoding: unicode
  database: olympos_development
  pool: 5
  username: lgorse
  password: 3times69

test:
  adapter: postgresql
  encoding: unicode
  database: olympos_test
  pool: 5
  username: lgorse
  password: 3times69

production:
  adapter: postgresql
  encoding: unicode
  database: olympos_production
  pool: 5
  username: lgorse
  password: 3times69
